adds a confirm event for non-redirected payments
vue-stripe/vue-stripe pull request #288
Opened 2022-07-10 05:50 UTC by AbrahamBrookes

2022-07-13 01:45 UTC, jofftiquez commented on src/elements/Payment.vue
> +        } else if( response.paymentIntent ) {
Please run through the linter. There should be a space between `if` and `(`. Thank you.

2022-07-13 01:46 UTC, jofftiquez commented on src/elements/Payment.vue
> +        const response = await this.stripe.confirmPayment({
Destructure the `error` and `paymentIntent` instead of using the `response` directly.

2022-07-13 01:47 UTC, jofftiquez commented on src/elements/Payment.vue
> +        if ( response.error ) {
Revert back after destructuring the `response`.

2022-07-13 01:47 UTC, jofftiquez requested changes
Hello @AbrahamBrookes thanks for this. There's just a few minor comments. I can merge this when they're fixed. Thank you so much!

2022-12-10 11:33 UTC, peterpacket commented
Hi, @jofftiquez

I created a new PR (https://github.com/vue-stripe/vue-stripe/pull/299) that fixes your comments. Maybe it slipped your attention. It would be awesome if you could take a look at it.

2023-02-06 03:08 UTC, merged