Initial Vue3 work
vue-stripe/vue-stripe pull request #308
Opened 2022-12-15 18:28 UTC by james090500

This build supports vue3 with basic functionality. Still some basic errors which need resolving but it at least works on vue3 for now. 

This is a temporary build until we can get something final together.

2023-01-04 17:49 UTC, james090500 commented
I fixed some render code and broken version code. This runs pretty optimal now to get you guys on vue3!

You can install with: ``npm i https://github.com/james090500/vue-stripe#james090500/vue3``

**IMPORTANT**
You MUST put the slot inside the element. 
These are breaking changes which confused me for a bit:

Vue 2:
```
<stripe-checkout :ref="this.type" :pk="this.pk" :session-id="this.sessionId"/>
<button class="btn btn-primary">Pay Now</button>
```

Vue 3:
```
<stripe-checkout :ref="this.type" :pk="this.pk" :session-id="this.sessionId">
      <button class="btn btn-primary">Pay Now</button>
 </stripe-checkout>
```

2023-02-06 03:06 UTC, jofftiquez commented
Thank you so much for this @james090500 really helpful while the official one is still in development. I have created a list of update in the vue 3 issue discussion. I just wanna say that I cannot merge this PR anymore as there are core changes to the version 5 and it's just a full rehaul really. Still thank you, I will keep this PR open until we finalized the new version. The vue 2 version is still going to be maintained for a while so if you have time any type of help would be appreciated. Thank you again.

2023-07-21 03:13 UTC, jofftiquez requested changes

2023-07-21 03:13 UTC, jofftiquez commented on README.md
Hi no need need to update the username in these links thanks

2023-07-21 03:13 UTC, jofftiquez commented on .vscode/extensions.json
Please remove

2023-07-21 03:13 UTC, jofftiquez commented on .eslintrc.cjs
Do not replace the original eslitrc file as it breaks all the intentional rules I have set to the project

2023-07-21 03:13 UTC, jofftiquez commented on babel.config.js
Why remove?

2023-07-21 03:13 UTC, jofftiquez commented on index.html
Hi, what's the purpose of this? Thanks

2023-07-21 03:13 UTC, jofftiquez commented on package-lock.json
Please remove, I am using yarn exclusively

2023-07-21 03:13 UTC, jofftiquez commented on package.json
> +  "homepage": "https://github.com/james090500/vue-stripe#readme",
Revert to the original

2023-07-21 03:13 UTC, jofftiquez commented on package.json
> +    "url": "https://github.com/james090500/vue-stripe/issues"
Revert to the original

2023-07-21 03:13 UTC, jofftiquez commented on package.json
> +    "url": "git@github.com:james090500/vue-stripe.git"
Revert to the original url

2023-07-21 03:13 UTC, jofftiquez commented on src/checkout/index.js
Fix lint formatting, don't use double quotes

2023-07-21 03:13 UTC, jofftiquez commented on src/elements/Payment.vue
> +      <mitB name="stripe-payment-element-errors">
What is `mitB` for?

2024-01-23 03:14 UTC, jofftiquez commented
Closing due to lack of response to the code review. Thank you

2024-01-23 03:14 UTC, closed without merging

2024-01-23 09:53 UTC, james090500 commented
Hi,

Sorry for the lack of response, this must have slipped through my emails. My changes to the username were so I could push a copy to npm for my code, I've realised better ways of doing this since then.

Hopefully my code was somewhat helpful anyway.

2024-01-23 09:56 UTC, jofftiquez commented
> Hi,
> 
> Sorry for the lack of response, this must have slipped through my emails. My changes to the username were so I could push a copy to npm for my code, I've realised better ways of doing this since then.
> 
> Hopefully my code was somewhat helpful anyway.

Hi, is surely did give me some ideas. Thank you so much.

2024-01-23 09:57 UTC, james090500 commented
No worries. Glad to have provided a temporary stopgap.